### ISSUE TITLE
[CI/CD] Issue를 Github project에 자동으로 할당하기

### ISSUE THREAD

**Issue by bennlee** [RootSearch/mood-tracker-app#9]
## Overview
새로운 issue open시 [Github project board](https://github.com/orgs/RootSearch/projects/1)에 자동으로 할당하기

## Detail
칸반보드로 프로젝트를 관리하고자, Github Project를 생성했으나 이슈 생성시 항상 프로젝트를 지정해주어야 하는 번거로움이 있음.
마켓에 올라와있는 [add-to-project](https://github.com/marketplace/actions/add-to-github-projects) 액션을 활용해서 이를 자동화해보자.

### 1. 액션 실행에 필요한 GITHUB PAT 준비

Fine-grained token이라는 repo or organization 단위의 scope를 지정할 수 있는 타입이 있지만, 현재 사용하려는 액션은 기존 classic type의 토큰밖에 지원하지 않음. (https://github.com/actions/add-to-project/issues/289)

classic type PAT은 repo or org단위 scope을 지정할 수 없기에, 보안상 문제가 될 수 있다고 판단 -> org official account를 이용해 key를 관리하기로 함.

### 2. `.github/workflows` 위치에 아래 yml 파일을 추가
```
name: Adds issues to project board

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0  # 버전은 적당히 현재기준 latest 로 선택했다.
        with:
          project-url: https://github.com/orgs/RootSearch/projects/1
          github-token: ${{ secrets.등록한 키 이름 }}
          # labeled: bug, needs-triage # 이런 형식으로 레이블과 조건을 걸 수 있음.
          # label-operator: NOT
```

### 3. 새로운 이슈를 생성하고, Action이 잘 실행되는지 확인

<img width="415" alt="image" src="https://user-images.githubusercontent.com/35001304/221408173-f49d3db9-44f7-4c92-be96-e368b22fd3f8.png">

### Ta-da! 🎉 

<img width="316" alt="image" src="https://user-images.githubusercontent.com/35001304/221408199-9132f064-13c1-41df-b229-73f4076bc14d.png">
